name: Build Android APK

on:
  workflow_dispatch: # این گزینه باعث می‌شود دکمه‌ای برای شروع دستی بیلد ظاهر شود
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: cd BandLockPro && chmod +x gradlew

    - name: Build with Gradle
      run: cd BandLockPro && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: BandLockPro-APK
        path: BandLockPro/app/build/outputs/apk/debug/app-debug.apk
